# [Character Name Here]

### Imports

In [6]:
import os

In [46]:
import story_simulator.config as ss_config
import story_simulator.world as story_world
import story_simulator.generator.language as language_generator
import story_simulator.generator.character as character_generator

### Setup

In [47]:
world_dir = os.path.join(
    ss_config.MODULE_DIR,
    'tests',
    'world_test_data',
)

In [48]:
# Load the world
w = story_world.World( world_dir )

In [50]:
# Generate the character
character = character_generator.GeneratedCharacter(
    world = w,
)

## Language

**TODO:** This needs to be filled in.

## Description

In [2]:
features = [
    'eye color',
    'hair color',
    'skin tone',
    'height',
    'weight',
    'ethnicity',
]

## Traits

In [61]:
# Generated traits
character.pos_traits

     Likelihood Description  Positivity
319           1       suave        1.25
281           1      placid        0.25

In [55]:
# Generated traits
character.neg_traits

    Likelihood Description  Positivity
50           1   fanatical       -1.00
73           1  inflexible       -0.75

In [62]:
# Overwrite the default character traits here
character.pos_traits = character.traits_table.loc[[319,281]]

In [63]:
# Overwrite the default character traits here
character.neg_traits = character.traits_table.loc[[50,73]]

## Quirks

In [66]:
character.quirks

    Likelihood                                        Description
10         1.0                                      Wears jewlery
53         1.0  Always doing something with their hands (e.g. ...

In [65]:
# Overwrite the generated character quirks here
character.quirks = character.quirks_table.loc[[10,53]]

## Goals

## Secrets

## Interactions

## Biography

In [3]:
biography_details = [
    'upbringing',
    'family members',
    'romantic history',
    'birthplace',
    'occupation',
    'education',
]

## Magic