# [Character Name Here]

### Imports

In [1]:
import os

In [2]:
import story_simulator.config as ss_config
import story_simulator.world as story_world
import story_simulator.generator.language as language_generator
import story_simulator.generator.character as character_generator

### Setup

In [3]:
world_dir = os.path.join(
    ss_config.MODULE_DIR,
    'tests',
    'world_test_data',
)

In [4]:
# Load the world
w = story_world.World( world_dir )

In [5]:
# Generate the character
character = character_generator.GeneratedCharacter(
    world = w,
)

## Language

**TODO:** This needs to be filled in.

## Description

In [6]:
features = [
    'eye color',
    'hair color',
    'hair type',
    'skin tone',
    'height',
    'build',
    'ethnicity',
]

## Traits

In [7]:
# Generated traits
character.pos_traits

     Likelihood Description  Positivity  Strength
192           1     careful         1.0         1
286           1     precise         1.0         1

In [8]:
# Generated traits
character.neg_traits

     Likelihood Description  Positivity  Strength
36            1    deatched        -0.5         1
140           1    slovenly        -0.5         1

In [9]:
# Overwrite the generated character traits here
character.pos_traits = character.traits_table.loc[[319,281]]

In [10]:
# Overwrite the generated character traits here
character.neg_traits = character.traits_table.loc[[50,73]]

## Quirks

In [11]:
character.quirks

    Likelihood                                   Description
15         1.0                    Consistently uncomfortable
37         1.0  Often walks weirdly (e.g. skips/marches/etc)

In [12]:
# Overwrite the generated character quirks here
character.quirks = character.quirks_table.loc[[10,53]]

## Goals

## Secrets

## Interactions

## Biography

In [13]:
biography_details = [
    'upbringing',
    'family members',
    'romantic history',
    'birthplace',
    'occupation',
    'education',
]

## Magic